# -*- coding: utf-8 -*-
import random

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3
import sys


class Ui_MainWindow(object):
    def __init__(self, db):
        self.db = db

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1361, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1090, 450, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(740, 500, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1220, 450, 101, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1080, 190, 239, 233))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 7, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1160, 20, 101, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 1011, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(920, 500, 101, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1250, 130, 61, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "新增员工"))
        self.pushButton_3.setText(_translate("MainWindow", "删除员工"))
        self.pushButton_4.setText(_translate("MainWindow", "修改信息"))
        self.comboBox.setItemText(0, _translate("MainWindow", "男"))
        self.comboBox.setItemText(1, _translate("MainWindow", "女"))
        self.label_3.setText(_translate("MainWindow", "年龄"))
        self.label_8.setText(_translate("MainWindow", "电话号码"))
        self.label_6.setText(_translate("MainWindow", "医护类别"))
        self.label_5.setText(_translate("MainWindow", "科室"))
        self.label_7.setText(_translate("MainWindow", "政治面貌"))
        self.label_2.setText(_translate("MainWindow", "姓名"))
        self.label_4.setText(_translate("MainWindow", "性别"))
        self.label.setText(_translate("MainWindow", "ID工号"))
        self.pushButton_5.setText(_translate("MainWindow", "随机抽取"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID工号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "年龄"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "性别"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "科室"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "医护类别"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "政治面貌"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "电话号码"))
        self.pushButton_6.setText(_translate("MainWindow", "列表显示"))
        self.pushButton.setText(_translate("MainWindow", "搜索"))

    def clear_lineEdit(self):
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()
        self.lineEdit_8.clear()

    def get_data(self):
        staff_id = self.lineEdit_2.text()
        name = self.lineEdit_3.text()
        age = self.lineEdit_4.text()
        gender = self.comboBox.currentText()
        department = self.lineEdit_5.text()
        category = self.lineEdit_6.text()
        politics = self.lineEdit_7.text()
        tele_num = self.lineEdit_8.text()
        return staff_id, name, age, gender, department, category, politics, tele_num

    def add_staff(self):
        # 获取输入框数据
        staff_id, name, age, gender, department, category, politics, tele_num = self.get_data()

        if not all([staff_id, name, str(age), gender, department, category, politics, tele_num]):
            QtWidgets.QMessageBox.warning(None, "警告", "请填写所有信息！")
            return

        # 检查工号是否已存在
        if self.db.exam_only_staff(staff_id):
            QtWidgets.QMessageBox.warning(None, "警告", "工号已存在！")
            return

        # 调用数据库添加方法
        self.db.add_staff(staff_id, name, age, gender, department, category, politics, tele_num)
        self.clear_lineEdit()

        self.show_all_staff()

        QtWidgets.QMessageBox.information(None, "提示", "添加成功！")

    def show_all_staff(self):
        staff = self.db.get_all_staff()
        self.tableWidget.setRowCount(len(staff))
        for row, staff in enumerate(staff):
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(staff[0]))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(staff[1]))
            self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(staff[2]))
            self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(staff[3]))
            self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(staff[4]))
            self.tableWidget.setItem(row, 5, QtWidgets.QTableWidgetItem(staff[5]))
            self.tableWidget.setItem(row, 6, QtWidgets.QTableWidgetItem(staff[6]))
            self.tableWidget.setItem(row, 7, QtWidgets.QTableWidgetItem(staff[7]))

    def search_staff(self):
        # 获取输入框中的信息
        staff_id, name, age, gender, department, category, politics, tele_num = self.get_data()
        value = [staff_id, name, age, gender, department, category, politics, tele_num]
        # 构建查询条件
        conditions = []
        if staff_id:
            conditions.append("id = ?")
        if name:
            conditions.append("name = ?")
        if age:
            conditions.append("age = ?")
        if gender:
            conditions.append("gender = ?")
        if department:
            conditions.append("department = ?")
        if category:
            conditions.append("category = ?")
        if politics:
            conditions.append("politics = ?")
        if tele_num:
            conditions.append("tele = ?")

        # 执行查询
        if conditions:
            staff = self.db.search_staff(conditions, value)
        else:
            staff = self.db.get_all_staff(self)

        if staff:
            # 将查询到的信息填充到表格中
            self.tableWidget.setRowCount(len(staff))
            for row, staff in enumerate(staff):
                self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(staff[0]))
                self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(staff[1]))
                self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(staff[2]))
                self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(staff[3]))
                self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(staff[4]))
                self.tableWidget.setItem(row, 5, QtWidgets.QTableWidgetItem(staff[5]))
                self.tableWidget.setItem(row, 6, QtWidgets.QTableWidgetItem(staff[6]))
                self.tableWidget.setItem(row, 7, QtWidgets.QTableWidgetItem(staff[7]))
        else:
            QtWidgets.QMessageBox.warning(None, "警告", "未找到该员工！")
        self.clear_lineEdit()

    def delete_staff(self):
        # 获取选中行的工号ID
        current_row = self.tableWidget.currentRow()
        if current_row == -1:
            QtWidgets.QMessageBox.warning(None, "警告", "请先选择要删除的员工！")
            return
        staff_id = self.tableWidget.item(current_row, 0).text()
        self.db.delete_staff_by_id(staff_id)

        # 更新表格
        self.show_all_staff()
        self.clear_lineEdit()
        QtWidgets.QMessageBox.information(None, "提示", "删除成功！")

    def modify_staff(self):
        current_row = self.tableWidget.currentRow()
        if current_row == -1:
            QtWidgets.QMessageBox.warning(None, "警告", "请先选择要修改的员工！")
            return

        # 获取选中员工的原始信息
        staff_id = self.lineEdit_2.text() if self.lineEdit_2.text() else self.tableWidget.item(current_row, 0).text()
        name = self.lineEdit_3.text() if self.lineEdit_3.text() else self.tableWidget.item(current_row, 1).text()
        age = self.lineEdit_4.text() if self.lineEdit_4.text() else self.tableWidget.item(current_row, 2).text()
        gender = self.comboBox.currentText()
        department = self.lineEdit_5.text() if self.lineEdit_5.text() else self.tableWidget.item(current_row, 4).text()
        category = self.lineEdit_6.text() if self.lineEdit_6.text() else self.tableWidget.item(current_row, 5).text()
        politics = self.lineEdit_7.text() if self.lineEdit_7.text() else self.tableWidget.item(current_row, 6).text()
        tele_num = self.lineEdit_8.text() if self.lineEdit_8.text() else self.tableWidget.item(current_row, 7).text()

        # 将原始信息填充到输入框中
        self.lineEdit_2.setText(staff_id)
        self.lineEdit_3.setText(name)
        self.lineEdit_4.setText(age)
        self.lineEdit_5.setText(department)
        self.lineEdit_6.setText(category)
        self.lineEdit_7.setText(politics)
        self.lineEdit_8.setText(tele_num)
        self.db.modify_staff(staff_id, name, age, gender, department, category, politics, tele_num)
        # 更新表格
        self.show_all_staff()

        QtWidgets.QMessageBox.information(None, "提示", "修改成功！")

    def random_staff(self):
        result = self.db.get_random_person()
        if result:
            # 显示一个信息框，通知用户抽取成功
            QtWidgets.QMessageBox.information(None, "",
                                              "抽取成功！选中的医务人员是: {}号 {}".format(result[0],result[1]))

    def setup_signals(self):
        self.pushButton.clicked.connect(self.search_staff)
        self.pushButton_2.clicked.connect(self.add_staff)
        self.pushButton_3.clicked.connect(self.delete_staff)
        self.pushButton_4.clicked.connect(self.modify_staff)
        self.pushButton_5.clicked.connect(self.random_staff)
        self.pushButton_6.clicked.connect(self.show_all_staff)


class DataBase:
    def __init__(self, dbname):
        self.dbname = dbname
        self.conn = None  # 初始化数据库连接
        self.cursor = None  # 初始化游标
        self.connect_db()  # 连接到数据库
        self.create_database()  # 创建表

    def connect_db(self):
        # 连接数据库
        self.conn = sqlite3.connect(self.dbname)
        self.cursor = self.conn.cursor()

    def create_database(self):
        # 创建表
        self.cursor.execute('''  
            CREATE TABLE IF NOT EXISTS staff (  
                id TEXT PRIMARY KEY,  
                name TEXT,  
                age TEXT,  
                gender TEXT,  
                department TEXT,  
                category TEXT,  
                politics TEXT,  
                tele_num TEXT  
            )  
        ''')
        self.conn.commit()

    def close_db(self):
        # 关闭数据库连接
        if self.conn:
            self.conn.close()
            self.conn = None  # 设置为 None 以避免再次尝试关闭

    def exam_only_staff(self, exam_id):
        self.cursor.execute("SELECT * FROM staff WHERE id = ?", (exam_id,))
        if not (self.cursor.fetchone()):
            return False
        return True

    def add_staff(self, id, name, age, gender, department, category, politics, tele_num):
        # 插入操作
        self.cursor.execute(
            "INSERT INTO staff (id, name, age, gender, department, category, politics, tele_num) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (id, name, age, gender, department, category, politics, tele_num)
        )
        self.conn.commit()

    def get_all_staff(self):
        self.cursor.execute("SELECT * FROM staff")
        result = self.cursor.fetchall()
        return result

    def search_staff(self, conditions, values):
        sql = "SELECT * FROM staff WHERE " + " AND ".join(conditions)
        self.cursor.execute(sql, [value for value in values if value])
        result = self.cursor.fetchall()
        return result

    def delete_staff_by_id(self, staff_id):
        self.cursor.execute("DELETE FROM staff WHERE id=?", (staff_id,))
        self.conn.commit()

    def modify_staff(self, staff_id, name, age, gender, department, category, politics, tele_num):
        self.cursor.execute(
            "UPDATE staff SET name=?, age=?, gender=?, department=?, category=?, politics=? ,tele_num=? WHERE id=?",
            (name, age, gender, department, category, politics, tele_num, staff_id))
        self.conn.commit()

    def get_random_person(self):
        staff = self.get_all_staff()
        # 如果没有人员信息，返回None
        if not staff:
            return None
        # 随机选择一个医务人员
        random_person = random.choice(staff)
        # 返回随机选择的医务人员信息
        return random_person

    def __del__(self):
        self.close_db()


if __name__ == "__main__":
    dbname = 'hospital_staff.db'
    db = DataBase(dbname)

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(db)
    ui.setupUi(MainWindow)
    ui.setup_signals()
    MainWindow.show()
    sys.exit(app.exec_())
